version: '3.1'

services:

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: dueton
      MYSQL_USER: spring
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql

# sudo docker run -it --network spring-backend_default --rm mariadb mysql -hspring-backend_mariadb_1 -mariadb -uroot -p
