version: '3.1'

services:

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: J6RAKz7fbgYhSM4d4Asz3ScjbLig4Jqk
      MYSQL_DATABASE: dueton
      MYSQL_USER: spring
      MYSQL_PASSWORD: tG9x9pCTdHmYeGy8knbxnX3KExj7rn4Y
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - /var/lib/mysql

# sudo docker run -it --network spring-backend_default --rm mariadb mysql -hspring-backend_mariadb_1 -uroot -pJ6RAKz7fbgYhSM4d4Asz3ScjbLig4Jqk
