server:
  port: 8081
  servlet:
    context-path: /api

spotify:
  client-id: 
  client-secret:

youtube:
  api-key:
  video-id-key: "\"videoId\": \""
  video-url-template: https://www.youtube.com/watch?v=

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
